[server]
bind = "0.0.0.0:8080"
auth_sqlite_path = "data/cori-auth.sqlite"

[auth]
mode = "embedded"

[auth.embedded]
admin_password = "changeme"

[auth.external]
issuer_url = "https://accounts.google.com"
client_id = "..."


