[package]
name = "cori"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
jsonschema.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

cori-core = { path = "../cori-core" }
cori-policy = { path = "../cori-policy" }
cori-runtime = { path = "../cori-runtime" }
cori-adapter-pg = { path = "../cori-adapter-pg" }
